# file k8s/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
  namespace: edu-helpai
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
